search_task:
  description: >
     Search for the latest cybersecurity news stories from trusted sources over the last 7 days for the date {date}.
      Focus on:
      - Data breaches and incidents
      - Vulnerabilities (CVEs) and zero-day exploits
      - Malware, ransomware, and emerging threats
      - APT groups and threat actor activities
      - Industry trends and regulatory changes
      - Critical infrastructure security
      - Cloud security developments
      - Notable cybersecurity research findings
      - Major security patches and updates
      - Significant policy/compliance changes
      
      Rate Limits: Respect website rate limits and implement delays between requests.
      Error Handling: Retry failed requests up to 3 times with exponential backoff.
    
  expected_output: >
    Formatted as markdown without ```
    A list of all the cybersecurity news stories for the last 7 days from the {date} with titles, source links (full path), and short but detailed summaries.

  agent: web_researcher

filter_task:
  description: >
    Analyse and filter the gathered news stories to determine which are most relevant to the target audience.
    Rank them based on:
    - Severity (Critical/High/Medium/Low)
    - Impact scope (Global/Regional/Industry-specific)
    - Public relevance score (1-10)
    - Technical complexity (Basic/Intermediate/Advanced)
  expected_output: >
    Formatted as markdown without ```
    A list of at least 15 news stories, sorted by importance. Each entry should include:
    - Title
    - Ranking
    - Short description (paragraph)
    - Source URL
    - Author (if known)
    if the author is not known, use the source URL as the author.
  agent: web_researcher

summarise_task:
  description: >
    Summarise the key details from each of the ranked filtered stories in filter_task.
    Extract critical information, such as what happened, who was impacted, and why it matters.
  expected_output: >
    Formatted as markdown without ```
    A summary document with concise key points for each story. Each story should include:
    - Headline
    - Key facts (What, Who, Why, and Impact)
    - Source URL
    - Author (if known)
    if the author is not known, use the source URL as the author.

  agent: web_researcher

weekly_overview_task:
  description: >
    Create a weekly overview of the cybersecurity news stories in filter_task, summarise_task, and trend_analysis_task.
  expected_output: >
    Formatted as markdown without ```
    A summary of the cybersecurity news stories for the week in filter_task, summarise_task, and trend_analysis_task .

  agent: web_researcher

cisa_kev_task:
  description: >
    run the cve_tool to get the KNOWN_EXPLOITS CISA Known Exploited Vulnerabilities for the last 7 days for the date {date} and review the results.
    write up a summary of the results and provide a list of the CISA KEV for the last 7 days for the date {date}.
  expected_output: >
    Formatted as markdown without ```
    A list of all the CISA KEV for the last 7 days for the date {date}.
  agent: web_researcher 

set_structured_output:
  description: >
    Set the output to be a structured output.
  expected_output: >
    Formatted as markdown without ```

    search_task: str = ""
    filter_task: str = ""
    summarise_task: str = ""
    weekly_overview_task: str = ""
    
  agent: web_researcher
