search_task:
  description: >
     Search for the latest cybersecurity news stories from trusted sources over the last 7 days for the date {date}.
      Focus on:
      - Data breaches and incidents
      - Vulnerabilities (CVEs) and zero-day exploits
      - Malware, ransomware, and emerging threats
      - APT groups and threat actor activities
      - Industry trends and regulatory changes
      - Critical infrastructure security
      - Cloud security developments
      - Notable cybersecurity research findings
      - Major security patches and updates
      - Significant policy/compliance changes
      
      Rate Limits: Respect website rate limits and implement delays between requests.
      Error Handling: Retry failed requests up to 3 times with exponential backoff.
    
  expected_output: >
     Structured output:
      search_task: [A list of all the cybersecurity news stories for the last 7 days from the {date} with titles, source links, and short summaries.]
  agent: web_researcher

filter_task:
  description: >
    Analyse and filter the gathered news stories to determine which are most relevant to the target audience.
    Rank them based on:
    - Severity (Critical/High/Medium/Low)
    - Impact scope (Global/Regional/Industry-specific)
    - Public relevance score (1-10)
    - Technical complexity (Basic/Intermediate/Advanced)
  expected_output: >
    Structured output

    filter_task: [A list of at least 15 news stories, sorted by importance. Each entry should include:
    - Title
    - Ranking
    - Short description (paragraph)
    - Source URL
    - Author (if known)]

    if the author is not known, use the source URL as the author.]
  agent: web_researcher

summarise_task:
  description: >
    Summarise the key details from each of the ranked filtered stories.
    Extract critical information, such as what happened, who was impacted, and why it matters.
  expected_output: >
    Structured output
    summarise_task: [A summary document with concise key points for each story. Each story should include:
    - Headline
    - Key facts (What, Who, Why, and Impact)
    - Source URL
    - Author (if known)]
    
    if the author is not known, use the source URL as the author.

  agent: web_researcher

trend_analysis_task:
  description: >
    Identify emerging patterns or trends across the cybersecurity news stories.
    Highlight any recurring threats, new vulnerabilities, or growing trends that should be noted.
    
    Analysis Requirements:
    - Minimum of 3 distinct trends identified
    - Statistical backing for trend identification
    - Compare with previous week's trends
    - Identify geographical impact patterns

  expected_output: >
    Structured output
    trend_analysis_task: [A report highlighting:
    - Key trends
    - Specific recurring topics or patterns
    - Notable insights for the cybersecurity audience
    - a table of the top 10 trends by news article.]
  agent: web_researcher

weekly_overview_task:
  description: >
    Create a weekly overview of the cybersecurity news stories.
  expected_output: >
    Structured output
    weekly_overview_task: [A summary of the cybersecurity news stories for the week.]
  agent: web_researcher
